version: '3.4'

services:
  database:
    image: mysql:5.7
    command: ['mysqld', '--character-set-server=utf8mb4', '--collation-server=utf8mb4_unicode_ci']
    environment:
      - MYSQL_DATABASE=foo
      - MYSQL_ROOT_PASSWORD=changeme
      - MYSQL_USER=foo
      - MYSQL_PASSWORD=changeme
      - TZ=Europe/Berlin
    volumes:
      - db-data:/var/lib/mysql:rw
    ports: ['3306']

volumes:
  db-data: {}
